export const categories = [
  { id: 'all', label: 'Все', icon: 'LayoutGrid' },
  { id: 'construction', label: 'Строительство', icon: 'Hammer' },
  { id: 'transport', label: 'Транспорт', icon: 'Car' },
  { id: 'it', label: 'IT', icon: 'Monitor' },
  { id: 'food', label: 'Еда и напитки', icon: 'UtensilsCrossed' },
  { id: 'education', label: 'Образование', icon: 'GraduationCap' },
  { id: 'beauty', label: 'Красота', icon: 'Sparkles' },
  { id: 'services', label: 'Услуги', icon: 'Wrench' },
  { id: 'trade', label: 'Торговля', icon: 'ShoppingBag' },
  { id: 'manufacturing', label: 'Производство', icon: 'Factory' },
  { id: 'security', label: 'Охрана', icon: 'Shield' },
]
export const featuredCompanies = [
  {
    id: '1',
    name: 'Бета Сторес',
    badge: 'Стабильный доход',
    logo: '🏪',
    banner: 'https://optimabank.kg/images/news/2020/04/optima24.jpg',
  },
  {
    id: '2',
    name: 'Шоро',
    badge: 'Большая команда',
    logo: '🍶',
    banner: 'https://bakai.kg/bbank/assets/posts/2025/7/29/post_QNisQBBjhadY3YH08ZDM.jpg',
  },
  {
    id: '3',
    name: 'Дордой Плаза',
    badge: 'Карьерный рост',
    logo: '🏬',
    banner: 'https://data.vb.kg/image/big/2024-02-02_19-59-56_677745.jpg',
  },
  {
    id: '4',
    name: 'Мегаком',
    badge: 'Соц. пакет',
    logo: '📱',
    banner: 'https://24.kg/thumbnails/451fa/cefbe/401905_w750_h_r.png',
  },
  {
    id: '5',
    name: 'Газпром Нефть',
    badge: 'Высокий оклад',
    logo: '⛽',
    banner:
      'https://www.akchabar.kg/_next/image?url=https%3A%2F%2Fakchabar-storage.fra1.digitaloceanspaces.com%2Fakchabar-storage%2Fmedia%2Fnews%2Fgalery%2F2024%2F08%2F25%2Fc6e9f9d1-7420-464d-bdf3-9a2c59f692c2.webp&w=2048&q=75',
  },
]


export const jobsData= [
  {
    id: "10",
    title: "UI/UX Дизайнер",
    company: "Tumar",
    city: "Бишкек",
    salary: "60 000 сом",
    salaryPeriod: "в месяц",
    date: "сегодня",
    views: 156,
    likes: 28,
    category: "it",
    experience: "1–3 года",
    schedule: "Полный день",
    remote: false,
    description: "Ищем талантливого дизайнера для работы над мобильными и веб-интерфейсами.",
    responsibilities: ["Проектирование пользовательских интерфейсов", "Создание прототипов и вайрфреймов", "Подготовка дизайн-макетов для разработки"],
    requirements: ["Опыт работы от 1 года", "Владение Figma", "Наличие портфолио"],
    conditions: ["Гибкий график", "Современный офис", "Профессиональный рост"],
  },
  {
    id: "11",
    title: "Менеджер по продажам",
    company: "Дордой Плаза",
    city: "Бишкек",
    salary: "40 000 сом",
    salaryPeriod: "в месяц",
    date: "сегодня",
    views: 432,
    likes: 56,
    category: "trade",
    experience: "Без опыта",
    schedule: "Полный день",
    remote: false,
    responsibilities: ["Поиск и привлечение новых клиентов", "Проведение презентаций и переговоров", "Заключение договоров"],
    requirements: ["Грамотная речь", "Опыт в продажах приветствуется", "Активность и целеустремленность"],
    conditions: ["Оклад + % от продаж", "Обучение за счет компании", "Дружный коллектив"],
  },
  {
    id: "12",
    title: "Системный администратор",
    company: "Beeline",
    city: "Бишкек",
    salary: "55 000 сом",
    salaryPeriod: "в месяц",
    date: "сегодня",
    views: 89,
    likes: 12,
    category: "it",
    experience: "3–6 лет",
    schedule: "Полный день",
    remote: false,
    responsibilities: ["Поддержка работоспособности сети и серверов", "Установка и настройка ПО", "Техническая поддержка пользователей"],
    requirements: ["Знание ОС Windows/Linux", "Опыт работы с сетевым оборудованием", "Понимание принципов информационной безопасности"],
    conditions: ["Стабильная зарплата", "Официальное трудоустройство", "График 5/2"],
  },
  {
    id: "1",
    title: "Frontend-разработчик",
    company: "Мегаком",
    city: "Бишкек",
    salary: "80 000 сом",
    salaryPeriod: "в месяц",
    date: "сегодня",
    views: 234,
    likes: 45,
    category: "it",
    experience: "1–3 года",
    schedule: "Полный день",
    remote: true,
    description: "Мы ищем Frontend-разработчика для работы над внутренними продуктами компании.",
    responsibilities: [
      "Разработка пользовательских интерфейсов на React",
      "Взаимодействие с дизайнерами и бэкенд-командой",
      "Код-ревью и написание тестов",
      "Оптимизация производительности приложений",
    ],
    requirements: [
      "Опыт работы с React от 1 года",
      "Знание TypeScript",
      "Понимание REST API",
      "Опыт с Git",
    ],
    conditions: [
      "Официальное оформление",
      "Гибкий график",
      "Возможность удалённой работы",
      "ДМС после испытательного срока",
    ],
    address: "ул. Киевская, 114",
  },
  {
    id: "2",
    title: "Продавец-консультант",
    company: "Бета Сторес",
    city: "Бишкек",
    salary: "25 000 сом",
    salaryPeriod: "в месяц",
    date: "вчера",
    views: 567,
    likes: 89,
    category: "trade",
    experience: "Без опыта",
    schedule: "Сменный график",
    remote: false,
    responsibilities: ["Консультирование покупателей", "Выкладка товара", "Работа с кассой"],
    requirements: ["Коммуникабельность", "Ответственность", "Возраст от 18 лет"],
    conditions: ["Бесплатное обучение", "Скидка на продукцию 30%"],
  },
  {
    id: "3",
    title: "Водитель категории B",
    company: "Яндекс Go",
    city: "Бишкек",
    salary: "1 500 сом",
    salaryPeriod: "в день",
    date: "сегодня",
    views: 1023,
    likes: 156,
    category: "transport",
    experience: "Менее 1 года",
    schedule: "Свободный график",
    remote: false,
    responsibilities: ["Перевозка пассажиров", "Поддержание автомобиля в чистоте"],
    requirements: ["Водительские права кат. B", "Стаж вождения от 1 года", "Личный автомобиль"],
  },
  {
    id: "4",
    title: "Повар-универсал",
    company: "Шоро",
    city: "Ош",
    salary: "30 000 сом",
    salaryPeriod: "в месяц",
    date: "2 дня назад",
    views: 345,
    likes: 67,
    category: "food",
    experience: "1–3 года",
    schedule: "Полный день",
    remote: false,
    responsibilities: ["Приготовление блюд согласно техкартам", "Соблюдение санитарных норм", "Контроль качества продуктов"],
    requirements: ["Опыт работы поваром от 1 года", "Наличие медицинской книжки", "Ответственность"],
    conditions: ["Бесплатное питание", "Сменный график", "Оплата переработок"],
  },
  {
    id: "5",
    title: "Охранник",
    company: "Дордой Плаза",
    city: "Бишкек",
    salary: "20 000 сом",
    salaryPeriod: "в месяц",
    date: "3 дня назад",
    views: 198,
    likes: 23,
    category: "security",
    experience: "Без опыта",
    schedule: "Сменный график",
    remote: false,
    responsibilities: ["Обеспечение безопасности на объекте", "Контрольно-пропускной режим", "Видеонаблюдение"],
    requirements: ["Физическая выносливость", "Дисциплинированность", "Опыт работы приветствуется"],
    conditions: ["График 2/2 или сутки/трое", "Предоставление формы", "Стабильные выплаты"],
  },
  {
    id: "6",
    title: "Учитель английского языка",
    company: "Oxford School",
    city: "Бишкек",
    salary: "35 000 сом",
    salaryPeriod: "в месяц",
    date: "сегодня",
    views: 412,
    likes: 78,
    category: "education",
    experience: "1–3 года",
    schedule: "Неполный день",
    remote: true,
    responsibilities: ["Проведение групповых и индивидуальных занятий", "Подготовка учебных материалов", "Проверка домашних заданий"],
    requirements: ["Уровень английского C1 и выше", "Педагогическое образование", "Умение находить подход к ученикам"],
    conditions: ["Удаленная работа", "Гибкий график", "Методическая поддержка"],
  },
  {
    id: "7",
    title: "Электрик-монтажник",
    company: "Газпром Нефть",
    city: "Бишкек",
    salary: "50 000 сом",
    salaryPeriod: "в месяц",
    date: "1 день назад",
    views: 156,
    likes: 12,
    category: "construction",
    experience: "3–6 лет",
    schedule: "Полный день",
    remote: false,
    address: "ул. Токтогула, 125/1",
    responsibilities: ["Монтаж электросетей и оборудования", "Поиск и устранение неисправностей", "Профилактические работы"],
    requirements: ["Профильное образование", "Группа допуска по электробезопасности", "Опыт работы от 3-х лет"],
    conditions: ["Обеспечение инструментом и спецодеждой", "Оплата проезда", "Надбавки за сложность"],
  },
  {
    id: "8",
    title: "Технолог пищевого производства",
    company: "Шоро",
    city: "Бишкек",
    salary: "45 000 сом",
    salaryPeriod: "в месяц",
    date: "сегодня",
    views: 89,
    likes: 5,
    category: "manufacturing",
    experience: "1–3 года",
    schedule: "Полный день",
    remote: false,
    responsibilities: ["Разработка новых рецептур", "Контроль технологического процесса", "Соблюдение стандартов качества"],
    requirements: ["Высшее профильное образование", "Знание требований СанПиН", "Опыт работы на производстве"],
    conditions: ["Официальное оформление", "Карьерный рост", "Корпоративные льготы"],
  },
  {
    id: "9",
    title: "Автомеханик",
    company: "Auto Center",
    city: "Ош",
    salary: "40 000 сом",
    salaryPeriod: "в месяц",
    date: "2 дня назад",
    views: 212,
    likes: 18,
    category: "services",
    experience: "1–3 года",
    schedule: "Полный день",
    remote: false,
    responsibilities: ["Диагностика и ремонт ходовой части", "Техническое обслуживание автомобилей", "Ремонт двигателей"],
    requirements: ["Знание устройства современных авто", "Опыт работы от 1 года", "Аккуратность"],
    conditions: ["Высокий процент от выработки", "Весь необходимый инструмент", "Теплый бокс"],
  },
];